version: '3.8'

services:
  ticket-service:
    build: ./ticket-service
    ports:
      - "5001:5001"
    depends_on:
      - queue-service
  queue-service:
    build: ./queue-service
    ports:
      - "5004:5004"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6380:6379"
  admin-service:
    build: ./admin-service
    ports:
      - "5002:5002"
    depends_on:
      - queue-service
  display-service:
    build: ./display-service
    ports:
      - "5003:5003"
    depends_on:
      - redis
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
  ticket-online-service:
    build: ./ticket-online-service
    ports:
      - "5005:5005"
    depends_on:
      - queue-service
      - redis
      - rabbitmq
